blog/urls.py
from django.urls import path
from .views import PublicationListView, PublicationDetailView

urlpatterns = [
    path('', PublicationListView.as_view(), name='publication-list'),
    path("publication/<int:pk>", PublicationDetailView.as_view(), name="publication-detail")
    
]

django_practica/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls"))
]

blog/models.py
from django.db import models

# Create your models here.
class Publication(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    body = models.TextField()

    def __str__(self):
        return self.title

blog/views.py
from django.views.generic import ListView, DetailView
from .models import Publication

# Create your views here.
class PublicationListView(ListView):
    model = Publication
    template_name = "publications-list.html"

class PublicationDetailView(DetailView):
    model = Publication
    template_name = "publication-detail.html" 

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Practica</title>
</head>
<body>
    <header>
        <h1>
            <a href="{% url 'publication-list' %}">Django Practica</a>
        </h1>
    </header> 
    <div>
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/publication-detail.html
{% extends '_base.html' %}

{% block content %}
    <article>
        <h2>{{ publication.title }}</h2>
        <p>{{ publication.author }}</p>
        <p>{{ publication.body }}</p>
    </article>
    {% endblock content %}

templates/publications-list.html
{% extends "_base.html" %}

{% block content %}
    <h2> Publications</h2>
    {% for post in publication_list %}
        <div>
            <ul>
                <li>
                    <h3><a href="{%url 'publication-detail' post.pk">{{ post.title }}</a></h3>
                    <p>Author: {{ post.author }}</p>
                </li>
            </ul>
        </div>
    {% endfor %}
{% endblock content %}